# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: ''
baseurl: ''
title: ''
description: 'Host site for the 2023 shared task on the lay summarization of biomedical research articles.'
permalink: pretty
logo: "https://drive.google.com/uc?export=view&id=1RNAKAll8lK6F67neSdVXUBkrjeHJfk36"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
# Header nav
navigation_header:
- title: Home
  url: /#intro
- title: Important dates
  url: /#dates
- title: Tasks
  url: /#task
- title: Datasets
  url: /#data
- title: Evaluation
  url: /#eval
- title: Organizers
  url: /#us

# Footer nav
navigation_footer:
- title: Back to top
  url: "#intro"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"


# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
