# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: ''
baseurl: ''
title: ''
description: 'Host site for BioLaySumm - the shared task on the lay summarization of biomedical research articles.'
permalink: pretty
# logo: "https://miniodis-rproxy.lisn.upsaclay.fr/coda-v2-prod-public/logos/2024-01-10-1704894122/319acff8a28b/logo.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: "#intro"
- title: Important dates
  url: "#dates"
- title: Tasks
  url: "#task"
- title: Datasets
  url: "#data"
- title: Evaluation
  url: "#eval"
- title: Organizers
  url: "#us"

# Footer nav
navigation_footer:
- title: Back to top
  url: "#intro"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"


custom_fonts:
  preconnect:
    - https://fonts.gstatic.com
  urls:
    - https://fonts.googleapis.com/css2?family=Rosario:wght@400;700&display=swap

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
